### ISSUE TITLE
LogUObjectBase: Error: 'this' pointer is invalid

### ISSUE THREAD

**Issue by N3GIS** [microdee/Uranium#3]
Please, after I compile your introduction, I run the case in the interface, and there is an error. Please how to solve this problem, the following error appears in the output window:
LogUObjectBase: Error: 'this' pointer is invalid.

![image](https://user-images.githubusercontent.com/7942057/126439234-011d317e-914c-4dec-8bd2-520d7bc7b268.png)
![1626847889](https://user-images.githubusercontent.com/7942057/126440280-aa9e825e-8e6b-49b5-b7ee-83c8dc682e7c.png)

**Comment by microdee** [comment]
I was dumb enough to accidentally exclude the necessary binaries from CEF distros. you should still see that error message for couple of frames but then it should stop when you get the proper texture

**Comment by N3GIS** [comment]
Thanks for the help, the performance is working on the latest version, as you introduced, performance has a big boost, though there are some bug, but does not affect normal use, overall the plugin is great, thanks again for the help.

**Comment by N3GIS** [comment]
The author has submitted the missing files and the problem is resolved
